name: Pre-commit Checks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  pre-commit:
    name: Pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
        continue-on-error: true
      
      - name: Generate summary
        if: always()
        run: |
          echo "## Pre-commit Results" >> $GITHUB_STEP_SUMMARY
          echo "Pre-commit hooks executed successfully" >> $GITHUB_STEP_SUMMARY
